/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface ApiAddcandidat {
    'home': RouterHistory;
  }
  interface ApiAddcandidatAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
  }

  interface SpiCandidat {}
  interface SpiCandidatAttributes extends StencilHTMLAttributes {}

  interface SpiEditcandidat {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface SpiEditcandidatAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiSearch {
    'match': MatchResults;
  }
  interface SpiSearchAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface SpiCandidats {}
  interface SpiCandidatsAttributes extends StencilHTMLAttributes {}

  interface SpiEnseignant {}
  interface SpiEnseignantAttributes extends StencilHTMLAttributes {}

  interface SpiEnseignants {}
  interface SpiEnseignantsAttributes extends StencilHTMLAttributes {}

  interface SpiFormation {}
  interface SpiFormationAttributes extends StencilHTMLAttributes {}

  interface SpiFormations {}
  interface SpiFormationsAttributes extends StencilHTMLAttributes {}

  interface SpiPromotion {}
  interface SpiPromotionAttributes extends StencilHTMLAttributes {}

  interface SpiPromotions {}
  interface SpiPromotionsAttributes extends StencilHTMLAttributes {}

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'ApiAddcandidat': Components.ApiAddcandidat;
    'SpiCandidat': Components.SpiCandidat;
    'SpiEditcandidat': Components.SpiEditcandidat;
    'SpiSearch': Components.SpiSearch;
    'SpiCandidats': Components.SpiCandidats;
    'SpiEnseignant': Components.SpiEnseignant;
    'SpiEnseignants': Components.SpiEnseignants;
    'SpiFormation': Components.SpiFormation;
    'SpiFormations': Components.SpiFormations;
    'SpiPromotion': Components.SpiPromotion;
    'SpiPromotions': Components.SpiPromotions;
    'SpiHeader': Components.SpiHeader;
    'SpiHome': Components.SpiHome;
    'SpiRoot': Components.SpiRoot;
  }

  interface StencilIntrinsicElements {
    'api-addcandidat': Components.ApiAddcandidatAttributes;
    'spi-candidat': Components.SpiCandidatAttributes;
    'spi-editcandidat': Components.SpiEditcandidatAttributes;
    'spi-search': Components.SpiSearchAttributes;
    'spi-candidats': Components.SpiCandidatsAttributes;
    'spi-enseignant': Components.SpiEnseignantAttributes;
    'spi-enseignants': Components.SpiEnseignantsAttributes;
    'spi-formation': Components.SpiFormationAttributes;
    'spi-formations': Components.SpiFormationsAttributes;
    'spi-promotion': Components.SpiPromotionAttributes;
    'spi-promotions': Components.SpiPromotionsAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-root': Components.SpiRootAttributes;
  }


  interface HTMLApiAddcandidatElement extends Components.ApiAddcandidat, HTMLStencilElement {}
  var HTMLApiAddcandidatElement: {
    prototype: HTMLApiAddcandidatElement;
    new (): HTMLApiAddcandidatElement;
  };

  interface HTMLSpiCandidatElement extends Components.SpiCandidat, HTMLStencilElement {}
  var HTMLSpiCandidatElement: {
    prototype: HTMLSpiCandidatElement;
    new (): HTMLSpiCandidatElement;
  };

  interface HTMLSpiEditcandidatElement extends Components.SpiEditcandidat, HTMLStencilElement {}
  var HTMLSpiEditcandidatElement: {
    prototype: HTMLSpiEditcandidatElement;
    new (): HTMLSpiEditcandidatElement;
  };

  interface HTMLSpiSearchElement extends Components.SpiSearch, HTMLStencilElement {}
  var HTMLSpiSearchElement: {
    prototype: HTMLSpiSearchElement;
    new (): HTMLSpiSearchElement;
  };

  interface HTMLSpiCandidatsElement extends Components.SpiCandidats, HTMLStencilElement {}
  var HTMLSpiCandidatsElement: {
    prototype: HTMLSpiCandidatsElement;
    new (): HTMLSpiCandidatsElement;
  };

  interface HTMLSpiEnseignantElement extends Components.SpiEnseignant, HTMLStencilElement {}
  var HTMLSpiEnseignantElement: {
    prototype: HTMLSpiEnseignantElement;
    new (): HTMLSpiEnseignantElement;
  };

  interface HTMLSpiEnseignantsElement extends Components.SpiEnseignants, HTMLStencilElement {}
  var HTMLSpiEnseignantsElement: {
    prototype: HTMLSpiEnseignantsElement;
    new (): HTMLSpiEnseignantsElement;
  };

  interface HTMLSpiFormationElement extends Components.SpiFormation, HTMLStencilElement {}
  var HTMLSpiFormationElement: {
    prototype: HTMLSpiFormationElement;
    new (): HTMLSpiFormationElement;
  };

  interface HTMLSpiFormationsElement extends Components.SpiFormations, HTMLStencilElement {}
  var HTMLSpiFormationsElement: {
    prototype: HTMLSpiFormationsElement;
    new (): HTMLSpiFormationsElement;
  };

  interface HTMLSpiPromotionElement extends Components.SpiPromotion, HTMLStencilElement {}
  var HTMLSpiPromotionElement: {
    prototype: HTMLSpiPromotionElement;
    new (): HTMLSpiPromotionElement;
  };

  interface HTMLSpiPromotionsElement extends Components.SpiPromotions, HTMLStencilElement {}
  var HTMLSpiPromotionsElement: {
    prototype: HTMLSpiPromotionsElement;
    new (): HTMLSpiPromotionsElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLElementTagNameMap {
    'api-addcandidat': HTMLApiAddcandidatElement
    'spi-candidat': HTMLSpiCandidatElement
    'spi-editcandidat': HTMLSpiEditcandidatElement
    'spi-search': HTMLSpiSearchElement
    'spi-candidats': HTMLSpiCandidatsElement
    'spi-enseignant': HTMLSpiEnseignantElement
    'spi-enseignants': HTMLSpiEnseignantsElement
    'spi-formation': HTMLSpiFormationElement
    'spi-formations': HTMLSpiFormationsElement
    'spi-promotion': HTMLSpiPromotionElement
    'spi-promotions': HTMLSpiPromotionsElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home': HTMLSpiHomeElement
    'spi-root': HTMLSpiRootElement
  }

  interface ElementTagNameMap {
    'api-addcandidat': HTMLApiAddcandidatElement;
    'spi-candidat': HTMLSpiCandidatElement;
    'spi-editcandidat': HTMLSpiEditcandidatElement;
    'spi-search': HTMLSpiSearchElement;
    'spi-candidats': HTMLSpiCandidatsElement;
    'spi-enseignant': HTMLSpiEnseignantElement;
    'spi-enseignants': HTMLSpiEnseignantsElement;
    'spi-formation': HTMLSpiFormationElement;
    'spi-formations': HTMLSpiFormationsElement;
    'spi-promotion': HTMLSpiPromotionElement;
    'spi-promotions': HTMLSpiPromotionsElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-root': HTMLSpiRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
